# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set environment variable for setting which project to build and test
      run: |
        echo "::set-env name=PROJECT_TO_TEST::$(sh scripts/test.sh)"
    
    - name: Read the env.PROJECT_TO_TEST
      run: |
        echo "env.PROJECT_TO_TEST = ${{ env.PROJECT_TO_TEST }}"
        
    - name: Conditionally Run
      if: contains('${{ env.PROJECT_TO_TEST }}', 'SomeString')
      run: |
        echo "SomeString did exist and should run"
    - name: Conditionally Run
      if: contains('${{ env.PROJECT_TO_TEST }}', 'ShouldNotRun')
      run: |
        echo "ShouldNotRun"      

